### ISSUE TITLE
Time to process requests is slow

### ISSUE THREAD

**Issue by ajuszczyk** [moneil/DSKTOOL-for-Learn#9]
We have tried to do a few changes lately with about 10 user enrolments. When we select the records then hit process course memberships the page just has the spinning circle and nothing happens.
Once we refresh the page, not all records have processed. We left it running for about 15 minutes on our staging Learn server and only 4/10 records had been processed. We have had similar happen on our live Learn server too.

**Comment by moneil** [comment]
Hrm. I have yet to experience this with any of the workflows and the access I have on the corporate SaaS demo server. I will close as not planned. If this continues to be a problem refile and we can dig into it.
